I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 92, in script
    define Character1 = Character(name, color = '#1F618D')
  File "game/script.rpy", line 92, in <module>
    define Character1 = Character(name, color = '#1F618D')
NameError: name 'name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 92, in script
    define Character1 = Character(name, color = '#1F618D')
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 2508, in execute
    self.set()
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\alexe\OneDrive\Рабочий стол\Ren'Py\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 92, in <module>
    define Character1 = Character(name, color = '#1F618D')
NameError: name 'name' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
IT princess_name_game 3.0
Thu Dec 21 21:02:18 2023
